### ISSUE TITLE
Null value throws error when sorting

### ISSUE THREAD

**Issue by vladshcherbin** [fantasyui-com/natural-sort-by-key#2]
Code:

```js
const byKey = require('natural-sort-by-key');

const nullTestArray = [
  { title: 'b' },
  { title: null },
  { title: 'a' }
]

console.log(nullTestArray.sort(byKey('title')))
```

Output:

```js
let B = b[key].toUpperCase();
               ^

TypeError: Cannot read property 'toUpperCase' of null
```

Null value throws an error when sorting.

**Comment by fantasyui-com** [comment]
There is no way to sort null values (there is no way to determine is null is above undefined, it makes no sense), and using extra assertions would slow the algorithm down. In 2.0 speed comes second to allowing nulls, so it works now.

**Comment by vladshcherbin** [comment]
It works as expected now 👍
